spring:
  application:
    name: spring-boot-logging-app

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/logging_db
    username: root
    password: 1234
  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql


server:
  port: 9090
